const hooks = require('hooks');

hooks.after('Resource > Update Resource', (transaction, done) => {
  try {
    JSON.parse('ğŸ’¥ boom ğŸ’¥');
  } catch (error) {
    transaction.fail = 'Unexpected exception in hooks';
    transaction.test = {
      start: transaction.test.start,
      end: transaction.test.end,
      duration: transaction.test.duration,
      startedAt: transaction.test.startedAt,
      message: transaction.fail
    };
  }
  done();
});
